development: 
   adapter: mysql2
   encoding: utf8 
   database: stats 
   user: root 
   password:  
   host: localhost
   reconnect: true

test: 
   adapter: mysql2
   encoding: utf8 
   database: stats_test
   user: root 
   password:  
   host: localhost
   reconnect: true